volumes:
  db_data:
  cache_data:
  s3_data:
  backend_data:
  backend_public_data:

services:
  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/db
    volumes:
      - db_data:/data
  
  cache:
    image: docker.io/library/redis:7
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - cache_data:/data
  
  s3:
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - s3_data:/data
    command: server /data --console-address ":9001"
  
  backend:
    depends_on: [s3, db, cache]
    image: docker.io/fabergonzalez16/libreria
    restart: unless-stopped
    build: .
    ports:
      - 8000:80
    env_file: .env
    volumes:
      - .:/var/www/html:z
      - backend_data:/var/www/html/storage

  frontend:
    depends_on: [backend]
    image: docker.io/fabergonzalez16/libreria-frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: frontend.Dockerfile
    command: npm run dev -- --host
    ports:
      - 5173:5173
    env_file: .env
    volumes:
      - .:/usr/src/app:z
